server:
  address: 0.0.0.0
  port: 8080
  servlet:
    session:
      timeout: 0
      cookie:
        name: NONE
        http-only: true
        secure: true

spring:
  web:
    locale: fr_CH
    locale-resolver: fixed
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/annonces}
      database: ${SPRING_DATA_MONGODB_DATABASE:annonces}
  thymeleaf:
    cache: false
  messages:
    basename: i18n/messages
    encoding: utf-8
    fallback-to-system-locale: false
  mail:
    host: 135.125.181.40
    port: 25
    protocol: smtp
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

app:
  jwt:
    issuer: annonces-app
    secret: "change-me-please-very-long-secrzet-key"
    expiration: 86400  # 1 jour en secondes
  upload:
    #dir: ${user.home}/annonces-uploads
    dir: /app/uploads